nanBlog/blogApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.home, name='home'),
    path('details/<str:titre>', views.detail, name='detail'),
    path('category/<str:titre>', views.categorie, name='categorie'),

    path('dashbord', views.dashbord, name='dashbord'),
    path('dashpost', views.dashpost, name='dashpost'),
    path('dashdetail/', views.dashdetail, name='dashdetail'),
    path('error', views.error, name='error'),
    path('ajout', views.ajout, name='ajout'),

    path('postsAtt', views.postsAtt, name='postsAtt'),
    path('postsV', views.postsV, name='postsV'),

]
  

nanBlog/comptesApp/urls.py
from django.urls import path
from . import views

app_name = 'comptes'
urlpatterns = [
    path("register/", views.register, name="register"),
    path("loginvisit/", views.login_visiteur, name="login_visit"),
    path("logout/", views.logout_view, name="logout_you"),
    path('profile/', views.element, name='profil_util'),
    path('modif_profil/', views.modif_profil, name='modif_profil'),
    path("registerapi", views.registerApi, name="registerapi"),
    path("loginapi", views.loginsApi, name="loginapi"),
]
  

nanBlog/contactApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'contact'
urlpatterns = [
    path('', views.contact, name='contact'),


]
  

nanBlog/nanBlog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf import settings

from django.conf.urls.static import static
from filebrowser.sites import site
from graphene_django.views import GraphQLView
from .schema import schema


urlpatterns = [
    path('admin/', admin.site.urls),
    path("graphql", GraphQLView.as_view(graphiql=True , schema=schema)),
    path('', include('blogApp.urls')),
    path('comptes/', include('comptesApp.urls')),
    path('configuration/', include('configurationApp.urls')),
    path('contact/', include('contactApp.urls')),
    path('site/', include('siteApp.urls')),
    path('statistique/', include('statistiqueApp.urls')),
    path('apirest/', include('api_rest.urls')),
    path('oauth/', include('social_django.urls', namespace="social")),
    path('tinymce/', include('tinymce.urls')),
    path('admin/filebrowser/', site.urls),
    path('accounts/', include('allauth.urls')),
    # url(r'^accounts/', include('allauth.urls')),
    # path('api/', include('api.urls')),
    # path("graphql", GraphQLView.as_view(graphiql=True, schema=schema)),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nanBlog/templates/bases/base.html
<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Favicon-->
	<link rel="shortcut icon" href="/static/img/fav.png">
	<!-- Author Meta -->
	<meta name="author" content="codepixer">
	<!-- Meta Description -->
	<meta name="description" content="">
	<!-- Meta Keyword -->
	<meta name="keywords" content="">
	<!-- meta character set -->
	<meta charset="UTF-8">
	<!-- Site Title -->
	<title>Ruft Blog</title>

	<link href="https://fonts.googleapis.com/css?family=Playfair+Display:700|Roboto:400,500" rel="stylesheet">
	<!--
			CSS
			============================================= -->
	<link rel="stylesheet" href="/static/css/linearicons.css">
	<link rel="stylesheet" href="/static/css/font-awesome.min.css">
	<link rel="stylesheet" href="/static/css/bootstrap.css">
	<link rel="stylesheet" href="/static/css/magnific-popup.css">
	<link rel="stylesheet" href="/static/css/nice-select.css">
	<link rel="stylesheet" href="/static/css/animate.min.css">
	<link rel="stylesheet" href="/static/css/owl.carousel.css">
    <link rel="stylesheet" href="/static/css/main.css">


	
	<script>
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>

<link href="/static/css/style.css" rel="stylesheet" type="text/css" media="all" />


</head>

<body>
	<div id="app">
	<!-- Start header Area -->
	<header id="header">
		<div class="container box_1170 main-menu">
			<div class="row align-items-center justify-content-between d-flex">
				<div id="logo">
					<a href="{% url 'blog:home' %}"><img src="/static/img/logo.png" alt="" title="" /></a>
				</div>
				<nav id="nav-menu-container">
					<ul class="nav-menu">
						<li class="menu-active"><a href="{% url 'blog:home' %}">Home</a></li>
						{% if user.is_authenticated %}
						<li><a href="{% url 'blog:dashbord' %}">Dashborad</a></li>
						{% else %}
						<li><a href="{% url 'comptes:register' %}">Register</a></li>
						<li><a href="{% url 'comptes:login_visit' %}">Login</a></li>
						{% endif %}
						<li><a href="{% url 'contact:contact' %}">Contact</a></li>
						{% if user.is_authenticated %}
						<li><a href="{% url 'comptes:logout_you' %}">Deconnexion</a></li>
						{% endif %}
					</ul>
				</nav>
			</div>
		</div>
	</header>
	<!-- End header Area -->

	
		{% block content %}
	
		{% endblock content %}
	
    
	<!-- start footer Area -->
	<footer class="footer-area section-gap">
		<div class="container box_1170">
			<div class="row">
				<div class="col-lg-3 col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6 class="footer_title">About Us</h6>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore dolore
							magna aliqua.</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6 class="footer_title">Newsletter</h6>
						<p>Stay updated with our latest trends</p>
						<div>
							<form class="subscribe_form relative">
								<div class="input-group d-flex flex-row">
									<input name="EMAIL" placeholder="Email Address" v-model="new_email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address '"
									 required="" type="email">
									<button v-on:click.prevent="Post_news" class="btn sub-btn"><span class="lnr lnr-arrow-right"></span></button>
								</div>
								<div class="mt-10 info"></div>
							</form>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 col-sm-6">
					<div class="single-footer-widget instafeed">
						<h6 class="footer_title">Instagram Feed</h6>
						<ul class="list instafeed d-flex flex-wrap">
							<li><img src="/static/img/i1.jpg" alt=""></li>
							<li><img src="/static/img/i2.jpg" alt=""></li>
							<li><img src="/static/img/i3.jpg" alt=""></li>
							<li><img src="/static/img/i4.jpg" alt=""></li>
							<li><img src="/static/img/i5.jpg" alt=""></li>
							<li><img src="/static/img/i6.jpg" alt=""></li>
							<li><img src="/static/img/i7.jpg" alt=""></li>
							<li><img src="/static/img/i8.jpg" alt=""></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-2 col-md-6 col-sm-6">
					<div class="single-footer-widget f_social_wd">
						<h6 class="footer_title">Follow Us</h6>
						<p>Let us be social</p>
						<div class="f_social">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-dribbble"></i></a>
							<a href="#"><i class="fa fa-behance"></i></a>
						</div>
					</div>
				</div>
			</div>
			
		</div>
	</footer>
	<!-- End footer Area -->
</div>

	<script src="/static/js/vendor/jquery-2.2.4.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
	 crossorigin="anonymous"></script>
	<script src="/static/js/vendor/bootstrap.min.js"></script>
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
	<script src="/static/js/easing.min.js"></script>
	<script src="/static/js/hoverIntent.js"></script>
	<script src="/static/js/superfish.min.js"></script>
	<script src="/static/js/jquery.ajaxchimp.min.js"></script>
	<script src="/static/js/jquery.magnific-popup.min.js"></script>
	<script src="/static/js/owl.carousel.min.js"></script>
	<script src="/static/js/jquery.nice-select.min.js"></script>
	<script src="/static/js/waypoints.min.js"></script>
	<script src="/static/js/mail-script.js"></script>
	<script src="/static/js/main.js"></script>

	<!-- VueJs et Axios -->
	<script src="/static/vuejs/vue.js"></script>
	<!-- <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script> --> <!-- C'est le cdn de VueJs mais j'ai opte pour vueJs en local -->
	
	<script src="/static/vuejs/axios-min.js"></script>
	<!-- Fin VueJs et Axios -->

	{% block vue %}
	{% endblock vue %}
	
	
	{% block vueregist %}
		
	{% endblock vueregist %}
		
	
</body>

</html>

nanBlog/templates/bases/baseslogin.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title> Nan Login </title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="/static/images4/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor4/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/fonts4/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/fonts4/iconic/css/material-design-iconic-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor4/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="/static/vendor4/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor4/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor4/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="/static/vendor4/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/css4/util.css">
	<link rel="stylesheet" type="text/css" href="/static/css4/main.css">
<!--===============================================================================================-->
</head>
<body>
	
    {% block content %}
	{% endblock content %}
	
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="/static/vendor4/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor4/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor4/bootstrap/js/popper.js"></script>
	<script src="/static/vendor4/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor4/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor4/daterangepicker/moment.min.js"></script>
	<script src="/static/vendor4/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor4/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="/static/js4/main.js"></script>

</body>
</html>