nanBlog/blogApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.home, name='home'),
    path('details/<str:titre>', views.detail, name='detail'),
    path('category/<str:titre>', views.categorie, name='categorie'),

    path('dashbord', views.dashbord, name='dashbord'),
    path('dashpost', views.dashpost, name='dashpost'),
    path('dashdetail/', views.dashdetail, name='dashdetail'),
    path('error', views.error, name='error'),
    path('ajout', views.ajout, name='ajout'),

    path('postsAtt', views.postsAtt, name='postsAtt'),
    path('postsV', views.postsV, name='postsV'),

]
  

nanBlog/nanBlog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf import settings

from django.conf.urls.static import static
from filebrowser.sites import site
from graphene_django.views import GraphQLView
from .schema import schema


urlpatterns = [
    path('admin/', admin.site.urls),
    path("graphql", GraphQLView.as_view(graphiql=True , schema=schema)),
    path('', include('blogApp.urls')),
    path('comptes/', include('comptesApp.urls')),
    path('configuration/', include('configurationApp.urls')),
    path('contact/', include('contactApp.urls')),
    path('site/', include('siteApp.urls')),
    path('statistique/', include('statistiqueApp.urls')),
    path('apirest/', include('api_rest.urls')),
    path('oauth/', include('social_django.urls', namespace="social")),
    path('tinymce/', include('tinymce.urls')),
    path('admin/filebrowser/', site.urls),
    path('accounts/', include('allauth.urls')),
    # url(r'^accounts/', include('allauth.urls')),
    # path('api/', include('api.urls')),
    # path("graphql", GraphQLView.as_view(graphiql=True, schema=schema)),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nanBlog/templates/pages/dashbord/attente.html
{% extends 'bases/base_dashbord.html' %}

{% block dashbord %}

    <!-- page content -->
    <div class="right_col" role="main">
        <div class="">
            <div class="page-title">
            <div class="title_left">
                <h3>Mes Articles<small> gallery design</small> </h3>
            </div>

                <div class="title_right">
                    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search for...">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">Go!</button>
                            </span>
                        </div>
                    </div>
                </div>

                <div class="form-group pull-right top_search" >
                    <div class="input-group-btn">
                      <span class="input-group-btn">
                        <a href="{% url 'blog:ajout' %}"><button class="btn btn-default" style="border-radius: 25px 25px 25px 25px!important;padding-left: 20px; padding-right: 20px;">Ajouter un Article</button></a>
                    </span>
                    </div>
                </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
            <div class="col-md-12">
                <div class="x_panel">
                <div class="x_title">
                    <h2>Media Gallery <small> gallery design </small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="#">Settings 1</a>
                            <a class="dropdown-item" href="#">Settings 2</a>
                        </div>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <div class="row">
                        {% for art in userpost %}
                        <div class="col-md-55">
                            <div class="thumbnail">
                            <div class="image view view-first">
                                <img style="width: 100%; display: block;" src="{{ art.photo.url }}" alt="image" />
                                <div class="mask">
                                <p>{{ art.categorie_id }}</p>
                                <div class="tools tools-bottom">
                                    <a href="{% url 'blog:dashdetail' %}"><i class="fa fa-link"></i></a>
                                    <a href="#"><i class="fa fa-pencil"></i></a>
                                    <a href="#"><i class="fa fa-times"></i></a>
                                </div>
                                </div>
                            </div>
                            <div class="caption">
                                <p>{{ art.description|truncatechars:70 }}</p>
                            </div>
                            </div>
                        </div>
                        {% endfor %}
                        
                    </div>
                </div>
                </div>
            </div>
            </div>

            <!-- <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <div class="x_panel">
                    <div class="x_title">
                        <h2><i class="fa fa-align-left"></i> Collapsible / Accordion <small>Sessions</small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="#">Settings 1</a>
                                <a class="dropdown-item" href="#">Settings 2</a>
                            </div>
                        </li>
                        <li><a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="accordion" id="accordion1" role="tablist" aria-multiselectable="true">
                        <div class="panel">
                            <a class="panel-heading" role="tab" id="headingOne1" data-toggle="collapse" data-parent="#accordion1" href="#collapseOne1" aria-expanded="true" aria-controls="collapseOne">
                            <h4 class="panel-title">Collapsible Group Item #1</h4>
                            </a>
                            <div id="collapseOne1" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                            <div class="panel-body">
                                <table class="table table-striped">
                                <thead>
                                    <tr>
                                    <th>#</th>
                                    <th>First Name</th>
                                    <th>Last Name</th>
                                    <th>Username</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                    <th scope="row">1</th>
                                    <td>Mark</td>
                                    <td>Otto</td>
                                    <td>@mdo</td>
                                    </tr>
                                    <tr>
                                    <th scope="row">2</th>
                                    <td>Jacob</td>
                                    <td>Thornton</td>
                                    <td>@fat</td>
                                    </tr>
                                    <tr>
                                    <th scope="row">3</th>
                                    <td>Larry</td>
                                    <td>the Bird</td>
                                    <td>@twitter</td>
                                    </tr>
                                </tbody>
                                </table>
                            </div>
                            </div>
                        </div>
                        <div class="panel">
                            <a class="panel-heading collapsed" role="tab" id="headingTwo1" data-toggle="collapse" data-parent="#accordion1" href="#collapseTwo1" aria-expanded="false" aria-controls="collapseTwo">
                            <h4 class="panel-title">Collapsible Group Item #2</h4>
                            </a>
                            <div id="collapseTwo1" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                            <div class="panel-body">
                                <p><strong>Collapsible Item 2 data</strong>
                                </p>
                                Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor,
                            </div>
                            </div>
                        </div>
                        <div class="panel">
                            <a class="panel-heading collapsed" role="tab" id="headingThree1" data-toggle="collapse" data-parent="#accordion1" href="#collapseThree1" aria-expanded="false" aria-controls="collapseThree">
                            <h4 class="panel-title">Collapsible Group Item #3</h4>
                            </a>
                            <div id="collapseThree1" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                            <div class="panel-body">
                                <p><strong>Collapsible Item 3 data</strong>
                                </p>
                                Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor
                            </div>
                            </div>
                        </div>
                        </div>
                        
                    </div>
                    </div>
                </div>
            </div> -->
        </div>
    </div>
    <!-- /page content -->

{% endblock dashbord %}

nanBlog/templates/pages/dashbord/page_404.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Gentelella Alela! | </title>

    <!-- Bootstrap -->
    <link href="/static/dashbord/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/static/dashbord/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/static/dashbord/vendors/nprogress/nprogress.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="/static/dashbord/build/css/custom.min.css" rel="stylesheet">
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <!-- page content -->
        <div class="col-md-12">
          <div class="col-middle">
            <div class="text-center text-center">
              <h1 class="error-number">404</h1>
              <h2>Sorry but we couldn't find this page</h2>
              <p>This page you are looking for does not exist <a href="{% url 'blog:home' %}">Retour au site</a></p>
              <div class="mid_center">
                <h3>Search</h3>
                <form>
                  <div class="col-xs-12 form-group pull-right top_search">
                    <div class="input-group">
                      <input type="text" class="form-control" placeholder="Search for...">
                      <span class="input-group-btn">
                              <button class="btn btn-secondary" type="button">Go!</button>
                          </span>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <!-- /page content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="/static/dashbord/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
   <script src="/static/dashbord/vendors/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- FastClick -->
    <script src="/static/dashbord/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="/static/dashbord/vendors/nprogress/nprogress.js"></script>

    <!-- Custom Theme Scripts -->
    <script src="/static/dashbord/build/js/custom.min.js"></script>
  </body>
</html>

nanBlog/templates/pages/dashbord/posts.html
{% extends 'bases/base_dashbord.html' %}

{% block dashbord %}

    <!-- page content -->
    <div class="right_col" role="main">
        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Mes Articles<small> gallery design</small> </h3>
            </div>

            <div class="title_right">
              <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                <div class="input-group">
                  <input type="text" class="form-control" placeholder="Search for...">
                  <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                  </span>
                </div>
              </div>
            </div>

            <div class="form-group pull-right top_search" >
                <div class="input-group-btn">
                  <span class="input-group-btn">
                    <a href="{% url 'blog:ajout' %}"><button class="btn btn-default" style="border-radius: 25px 25px 25px 25px!important;padding-left: 20px; padding-right: 20px;">Ajouter un Article</button></a>
                </span>
                </div>
            </div>
            
          </div>

          <div class="clearfix"></div>

          <div class="row">
            <div class="col-md-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>Media Gallery <small> gallery design </small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                          <a class="dropdown-item" href="#">Settings 1</a>
                          <a class="dropdown-item" href="#">Settings 2</a>
                        </div>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    
                  <div class="row">
                      {% for art in userpost %}
                    <div class="col-md-55">
                      <div class="thumbnail">
                        <div class="image view view-first">
                          <img style="width: 100%; display: block;" src="{{ art.photo.url }}" alt="image" />
                          <div class="mask">
                            <p>{{ art.categorie_id }}</p>
                            <div class="tools tools-bottom">
                              <a href="{% url 'blog:dashdetail' %}"><i class="fa fa-link"></i></a>
                              <a href="#"><i class="fa fa-pencil"></i></a>
                              <a href="#"><i class="fa fa-times"></i></a>
                            </div>
                          </div>
                        </div>
                        <div class="caption">
                          <p>{{ art.description|truncatechars:85 }}</p>
                        </div>
                      </div>
                    </div>
                    {% endfor %}
                  </div>
                  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /page content -->

{% endblock dashbord %}

nanBlog/templates/pages/dashbord/postsAtt.html
{% extends 'bases/base_dashbord.html' %}

{% block dashbord %}

    <!-- page content -->
    <div class="right_col" role="main">
        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Mes Articles<small> gallery design</small> </h3>
            </div>

            <div class="title_right">
              <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                <div class="input-group">
                  <input type="text" class="form-control" placeholder="Search for...">
                  <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                  </span>
                </div>
              </div>
            </div>

            <div class="form-group pull-right top_search" >
                <div class="input-group-btn">
                  <span class="input-group-btn">
                    <a href="{% url 'blog:ajout' %}"><button class="btn btn-default" style="border-radius: 25px 25px 25px 25px!important;padding-left: 20px; padding-right: 20px;">Ajouter un Article</button></a>
                </span>
                </div>
            </div>
            
          </div>

          <div class="clearfix"></div>

          <div class="row">
            <div class="col-md-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>Media Gallery <small> gallery design </small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                          <a class="dropdown-item" href="#">Settings 1</a>
                          <a class="dropdown-item" href="#">Settings 2</a>
                        </div>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    
                  <div class="row">
                      {% for art in c %}
                    <div class="col-md-55">
                      <div class="thumbnail">
                        <div class="image view view-first">
                          <img style="width: 100%; display: block;" src="{{ art.photo.url }}" alt="image" />
                          <div class="mask">
                            <p>{{ art.categorie_id }}</p>
                            <div class="tools tools-bottom">
                              <a href="{% url 'blog:dashdetail' %}"><i class="fa fa-link"></i></a>
                              <a href="#"><i class="fa fa-pencil"></i></a>
                              <a href="#"><i class="fa fa-times"></i></a>
                            </div>
                          </div>
                        </div>
                        <div class="caption">
                          <p>{{ art.description|truncatechars:85 }}</p>
                        </div>
                      </div>
                    </div>
                    {% endfor %}
                  </div>
                  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /page content -->

{% endblock dashbord %}

nanBlog/templates/pages/dashbord/postsV.html
{% extends 'bases/base_dashbord.html' %}

{% block dashbord %}

    <!-- page content -->
    <div class="right_col" role="main">
        <div class="">
          <div class="page-title">
            <div class="title_left">
              <h3>Mes Articles<small> gallery design</small> </h3>
            </div>

            <div class="title_right">
              <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                <div class="input-group">
                  <input type="text" class="form-control" placeholder="Search for...">
                  <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                  </span>
                </div>
              </div>
            </div>

            <div class="form-group pull-right top_search" >
                <div class="input-group-btn">
                  <span class="input-group-btn">
                    <a href="{% url 'blog:ajout' %}"><button class="btn btn-default" style="border-radius: 25px 25px 25px 25px!important;padding-left: 20px; padding-right: 20px;">Ajouter un Article</button></a>
                </span>
                </div>
            </div>
            
          </div>

          <div class="clearfix"></div>

          <div class="row">
            <div class="col-md-12">
              <div class="x_panel">
                <div class="x_title">
                  <h2>Media Gallery <small> gallery design </small></h2>
                  <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                          <a class="dropdown-item" href="#">Settings 1</a>
                          <a class="dropdown-item" href="#">Settings 2</a>
                        </div>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                  </ul>
                  <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    
                  <div class="row">
                      {% for art in b %}
                    <div class="col-md-55">
                      <div class="thumbnail">
                        <div class="image view view-first">
                          <img style="width: 100%; display: block;" src="{{ art.photo.url }}" alt="image" />
                          <div class="mask">
                            <p>{{ art.categorie_id }}</p>
                            <div class="tools tools-bottom">
                              <a href="{% url 'blog:dashdetail' %}"><i class="fa fa-link"></i></a>
                              <a href="#"><i class="fa fa-pencil"></i></a>
                              <a href="#"><i class="fa fa-times"></i></a>
                            </div>
                          </div>
                        </div>
                        <div class="caption">
                          <p>{{ art.description|truncatechars:85 }}</p>
                        </div>
                      </div>
                    </div>
                    {% endfor %}
                  </div>
                  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /page content -->

{% endblock dashbord %}